In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ulrikthygepedersen/speed-dating")

print("Path to dataset files:", path)

/home/user1/miniconda3/envs/pandas/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading from https://www.kaggle.com/api/v1/datasets/download/ulrikthygepedersen/speed-dating?dataset_version_number=1...

100%|██████████| 434k/434k [00:00<00:00, 2.00MB/s]

Extracting files...
Path to dataset files: /home/user1/.cache/kagglehub/datasets/ulrikthygepedersen/speed-dating/versions/1

In [2]:
type(path)

str

In [5]:
import pandas as pd
import os

# 데이터셋 파일 목록 확인
print(os.listdir(path))

['speeddating.csv']

In [7]:
df = pd.read_csv(path+'/speeddating.csv')

In [9]:
df.describe

<bound method NDFrame.describe of      has_null  wave     gender   age  age_o  d_age   d_d_age  \
0         b''   1.0  b'female'  21.0   27.0    6.0  b'[4-6]'
1         b''   1.0  b'female'  21.0   22.0    1.0  b'[0-1]'
2         b''   1.0  b'female'  21.0   22.0    1.0  b'[0-1]'
3         b''   1.0  b'female'  21.0   23.0    2.0  b'[2-3]'
4         b''   1.0  b'female'  21.0   24.0    3.0  b'[2-3]'
...       ...   ...        ...   ...    ...    ...       ...
8373      b''  21.0    b'male'  25.0   26.0    1.0  b'[0-1]'
8374      b''  21.0    b'male'  25.0   24.0    1.0  b'[0-1]'
8375      b''  21.0    b'male'  25.0   29.0    4.0  b'[4-6]'
8376      b''  21.0    b'male'  25.0   22.0    3.0  b'[2-3]'
8377      b''  21.0    b'male'  25.0   22.0    3.0  b'[2-3]'

                                          race  \
0     b'Asian/Pacific Islander/Asian-American'
1     b'Asian/Pacific Islander/Asian-American'
2     b'Asian/Pacific Islander/Asian-American'
3     b'Asian/Pacific Islander/Asian-American'
4     b'Asian/Pacific Islander/Asian-American'
...                                        ...
8373            b'European/Caucasian-American'
8374            b'European/Caucasian-American'
8375            b'European/Caucasian-American'
8376            b'European/Caucasian-American'
8377            b'European/Caucasian-American'

                                        race_o samerace  ...  \
0               b'European/Caucasian-American'     b'0'  ...
1               b'European/Caucasian-American'     b'0'  ...
2     b'Asian/Pacific Islander/Asian-American'     b'1'  ...
3               b'European/Caucasian-American'     b'0'  ...
4                  b'Latino/Hispanic American'     b'0'  ...
...                                        ...      ...  ...
8373               b'Latino/Hispanic American'     b'0'  ...
8374                                  b'Other'     b'0'  ...
8375               b'Latino/Hispanic American'     b'0'  ...
8376  b'Asian/Pacific Islander/Asian-American'     b'0'  ...
8377  b'Asian/Pacific Islander/Asian-American'     b'0'  ...

      d_expected_num_interested_in_me  d_expected_num_matches like  \
0                            b'[0-3]'                b'[3-5]'  7.0
1                            b'[0-3]'                b'[3-5]'  7.0
2                            b'[0-3]'                b'[3-5]'  7.0
3                            b'[0-3]'                b'[3-5]'  7.0
4                            b'[0-3]'                b'[3-5]'  6.0
...                               ...                     ...  ...
8373                         b'[0-3]'                b'[3-5]'  2.0
8374                         b'[0-3]'                b'[3-5]'  4.0
8375                         b'[0-3]'                b'[3-5]'  6.0
8376                         b'[0-3]'                b'[3-5]'  5.0
8377                         b'[0-3]'                b'[3-5]'  4.0

     guess_prob_liked    d_like  d_guess_prob_liked  met  decision  \
0                 6.0  b'[6-8]'            b'[5-6]'  0.0      b'1'
1                 5.0  b'[6-8]'            b'[5-6]'  1.0      b'1'
2                 NaN  b'[6-8]'            b'[0-4]'  1.0      b'1'
3                 6.0  b'[6-8]'            b'[5-6]'  0.0      b'1'
4                 6.0  b'[6-8]'            b'[5-6]'  0.0      b'1'
...               ...       ...                 ...  ...       ...
8373              5.0  b'[0-5]'            b'[5-6]'  0.0      b'0'
8374              4.0  b'[0-5]'            b'[0-4]'  0.0      b'0'
8375              5.0  b'[6-8]'            b'[5-6]'  0.0      b'0'
8376              5.0  b'[0-5]'            b'[5-6]'  0.0      b'0'
8377              5.0  b'[0-5]'            b'[5-6]'  0.0      b'0'

      decision_o  match
0           b'0'   b'0'
1           b'0'   b'0'
2           b'1'   b'1'
3           b'1'   b'1'
4           b'1'   b'1'
...          ...    ...
8373        b'1'   b'0'
8374        b'0'   b'0'
8375        b'0'   b'0'
8376        b'1'   b'0'
8377        b'1'   b'0'

[8378 rows x 123 columns]>

In [10]:
df.shape

(8378, 123)

In [11]:
df.head(2)

,has_null,wave,gender,age,age_o,d_age,d_d_age,race,race_o,samerace,...,d_expected_num_interested_in_me,d_expected_num_matches,like,guess_prob_liked,d_like,d_guess_prob_liked,met,decision,decision_o,match
0,b'',1.0,b'female',21.0,27.0,6.0,b'[4-6]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',7.0,6.0,b'[6-8]',b'[5-6]',0.0,b'1',b'0',b'0'
1,b'',1.0,b'female',21.0,22.0,1.0,b'[0-1]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',7.0,5.0,b'[6-8]',b'[5-6]',1.0,b'1',b'0',b'0'

In [14]:
df.loc[:, (df.dtypes =='object').values]

,has_null,gender,d_d_age,race,race_o,samerace,d_importance_same_race,d_importance_same_religion,field,d_pref_o_attractive,...,d_yoga,d_interests_correlate,d_expected_happy_with_sd_people,d_expected_num_interested_in_me,d_expected_num_matches,d_like,d_guess_prob_liked,decision,decision_o,match
0,b'',b'female',b'[4-6]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',b'[2-5]',b'[2-5]',b'Law',b'[21-100]',...,b'[0-5]',b'[0-0.33]',b'[0-4]',b'[0-3]',b'[3-5]',b'[6-8]',b'[5-6]',b'1',b'0',b'0'
1,b'',b'female',b'[0-1]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',b'[2-5]',b'[2-5]',b'Law',b'[21-100]',...,b'[0-5]',b'[0.33-1]',b'[0-4]',b'[0-3]',b'[3-5]',b'[6-8]',b'[5-6]',b'1',b'0',b'0'
2,b'',b'female',b'[0-1]',b'Asian/Pacific Islander/Asian-American',b'Asian/Pacific Islander/Asian-American',b'1',b'[2-5]',b'[2-5]',b'Law',b'[16-20]',...,b'[0-5]',b'[0-0.33]',b'[0-4]',b'[0-3]',b'[3-5]',b'[6-8]',b'[0-4]',b'1',b'1',b'1'
3,b'',b'female',b'[2-3]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',b'[2-5]',b'[2-5]',b'Law',b'[21-100]',...,b'[0-5]',b'[0.33-1]',b'[0-4]',b'[0-3]',b'[3-5]',b'[6-8]',b'[5-6]',b'1',b'1',b'1'
4,b'',b'female',b'[2-3]',b'Asian/Pacific Islander/Asian-American',b'Latino/Hispanic American',b'0',b'[2-5]',b'[2-5]',b'Law',b'[21-100]',...,b'[0-5]',b'[0-0.33]',b'[0-4]',b'[0-3]',b'[3-5]',b'[6-8]',b'[5-6]',b'1',b'1',b'1'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,b'',b'male',b'[0-1]',b'European/Caucasian-American',b'Latino/Hispanic American',b'0',b'[0-1]',b'[0-1]',b'Climate Dynamics',b'[0-15]',...,b'[0-5]',b'[0.33-1]',b'[7-10]',b'[0-3]',b'[3-5]',b'[0-5]',b'[5-6]',b'0',b'1',b'0'
8374,b'',b'male',b'[0-1]',b'European/Caucasian-American',b'Other',b'0',b'[0-1]',b'[0-1]',b'Climate Dynamics',b'[21-100]',...,b'[0-5]',b'[0.33-1]',b'[7-10]',b'[0-3]',b'[3-5]',b'[0-5]',b'[0-4]',b'0',b'0',b'0'
8375,b'',b'male',b'[4-6]',b'European/Caucasian-American',b'Latino/Hispanic American',b'0',b'[0-1]',b'[0-1]',b'Climate Dynamics',b'[21-100]',...,b'[0-5]',b'[-1-0]',b'[7-10]',b'[0-3]',b'[3-5]',b'[6-8]',b'[5-6]',b'0',b'0',b'0'
8376,b'',b'male',b'[2-3]',b'European/Caucasian-American',b'Asian/Pacific Islander/Asian-American',b'0',b'[0-1]',b'[0-1]',b'Climate Dynamics',b'[0-15]',...,b'[0-5]',b'[0.33-1]',b'[7-10]',b'[0-3]',b'[3-5]',b'[0-5]',b'[5-6]',b'0',b'1',b'0'
8377,b'',b'male',b'[2-3]',b'European/Caucasian-American',b'Asian/Pacific Islander/Asian-American',b'0',b'[0-1]',b'[0-1]',b'Climate Dynamics',b'[16-20]',...,b'[0-5]',b'[0-0.33]',b'[7-10]',b'[0-3]',b'[3-5]',b'[0-5]',b'[5-6]',b'0',b'1',b'0'

In [16]:
(df.dtypes =='object').values.shape

(123,)

In [ ]:
#칼럼에만 마스크 적용
df.loc[:, (df.dtypes =='object').values].map(lambda x: x.replace("b'", ''))

,has_null,gender,d_d_age,race,race_o,samerace,d_importance_same_race,d_importance_same_religion,field,d_pref_o_attractive,...,d_yoga,d_interests_correlate,d_expected_happy_with_sd_people,d_expected_num_interested_in_me,d_expected_num_matches,d_like,d_guess_prob_liked,decision,decision_o,match
0,',female',[4-6]',Asian/Pacific Islander/Asian-American',European/Caucasian-American',0',[2-5]',[2-5]',Law',[21-100]',...,[0-5]',[0-0.33]',[0-4]',[0-3]',[3-5]',[6-8]',[5-6]',1',0',0'
1,',female',[0-1]',Asian/Pacific Islander/Asian-American',European/Caucasian-American',0',[2-5]',[2-5]',Law',[21-100]',...,[0-5]',[0.33-1]',[0-4]',[0-3]',[3-5]',[6-8]',[5-6]',1',0',0'
2,',female',[0-1]',Asian/Pacific Islander/Asian-American',Asian/Pacific Islander/Asian-American',1',[2-5]',[2-5]',Law',[16-20]',...,[0-5]',[0-0.33]',[0-4]',[0-3]',[3-5]',[6-8]',[0-4]',1',1',1'
3,',female',[2-3]',Asian/Pacific Islander/Asian-American',European/Caucasian-American',0',[2-5]',[2-5]',Law',[21-100]',...,[0-5]',[0.33-1]',[0-4]',[0-3]',[3-5]',[6-8]',[5-6]',1',1',1'
4,',female',[2-3]',Asian/Pacific Islander/Asian-American',Latino/Hispanic American',0',[2-5]',[2-5]',Law',[21-100]',...,[0-5]',[0-0.33]',[0-4]',[0-3]',[3-5]',[6-8]',[5-6]',1',1',1'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,',male',[0-1]',European/Caucasian-American',Latino/Hispanic American',0',[0-1]',[0-1]',Climate Dynamics',[0-15]',...,[0-5]',[0.33-1]',[7-10]',[0-3]',[3-5]',[0-5]',[5-6]',0',1',0'
8374,',male',[0-1]',European/Caucasian-American',Other',0',[0-1]',[0-1]',Climate Dynamics',[21-100]',...,[0-5]',[0.33-1]',[7-10]',[0-3]',[3-5]',[0-5]',[0-4]',0',0',0'
8375,',male',[4-6]',European/Caucasian-American',Latino/Hispanic American',0',[0-1]',[0-1]',Climate Dynamics',[21-100]',...,[0-5]',[-1-0]',[7-10]',[0-3]',[3-5]',[6-8]',[5-6]',0',0',0'
8376,',male',[2-3]',European/Caucasian-American',Asian/Pacific Islander/Asian-American',0',[0-1]',[0-1]',Climate Dynamics',[0-15]',...,[0-5]',[0.33-1]',[7-10]',[0-3]',[3-5]',[0-5]',[5-6]',0',1',0'
8377,',male',[2-3]',European/Caucasian-American',Asian/Pacific Islander/Asian-American',0',[0-1]',[0-1]',Climate Dynamics',[16-20]',...,[0-5]',[0-0.33]',[7-10]',[0-3]',[3-5]',[0-5]',[5-6]',0',1',0'

In [21]:
a = pd.Series(df.iloc[1,:])
a

has_null                    b''
wave                        1.0
gender                b'female'
age                        21.0
age_o                      22.0
                        ...
d_guess_prob_liked     b'[5-6]'
met                         1.0
decision                   b'1'
decision_o                 b'0'
match                      b'0'
Name: 1, Length: 123, dtype: object

In [22]:
df.loc[:, (df.dtypes == 'object').values] = df.loc[:, (df.dtypes == 'object').values].map(lambda x: x.replace("b'", '').replace("'", ""))

In [23]:
df.columns

Index(['has_null', 'wave', 'gender', 'age', 'age_o', 'd_age', 'd_d_age',
       'race', 'race_o', 'samerace',
       ...
       'd_expected_num_interested_in_me', 'd_expected_num_matches', 'like',
       'guess_prob_liked', 'd_like', 'd_guess_prob_liked', 'met', 'decision',
       'decision_o', 'match'],
      dtype='object', length=123)

In [26]:
unique_sum_per_column = df.apply(lambda col: col.unique().sum())

print(unique_sum_per_column)

has_null
wave                             231.0
gender                      femalemale
age                                NaN
age_o                              NaN
                            ...
d_guess_prob_liked    [5-6][0-4][7-10]
met                                NaN
decision                            10
decision_o                          01
match                               01
Length: 123, dtype: object

In [27]:
unique_counts = df.nunique()
print(unique_counts)

has_null               1
wave                  21
gender                 2
age                   24
age_o                 24
                      ..
d_guess_prob_liked     3
met                    7
decision               2
decision_o             2
match                  2
Length: 123, dtype: int64

In [ ]:
import pandas as pd

# 컬럼 최대 출력 개수 늘리기 (None: 제한 없음)
pd.set_option('display.max_columns', None)

has_null               1
wave                  21
gender                 2
age                   24
age_o                 24
                      ..
d_guess_prob_liked     3
met                    7
decision               2
decision_o             2
match                  2
Length: 123, dtype: int64

In [29]:
# 이제 모든 컬럼이 출력됩니다
print(df.nunique())

has_null               1
wave                  21
gender                 2
age                   24
age_o                 24
                      ..
d_guess_prob_liked     3
met                    7
decision               2
decision_o             2
match                  2
Length: 123, dtype: int64

In [30]:
import pandas as pd
import numpy as np

# 컬럼 제한은 10개로, 시리즈 값은 모두 출력
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_seq_item', None)

# 예시 데이터프레임 생성 (실제 데이터프레임 df로 대체)
np.random.seed(0)
df = pd.DataFrame(np.random.randint(0, 100, size=(8378, 123)), columns=[f'col_{i}' for i in range(123)])

# 각 컬럼별 유니크 값 개수 계산
unique_counts = df.nunique()

# 123개 값이 모두 출력됨
print(unique_counts)

col_0      100
col_1      100
col_2      100
col_3      100
col_4      100
          ...
col_118    100
col_119    100
col_120    100
col_121    100
col_122    100
Length: 123, dtype: int64

In [34]:
type(unique_counts)

pandas.core.series.Series

In [36]:
import pandas as pd

# 시리즈 전체 출력 옵션 설정
pd.set_option('display.max_rows', None)

In [39]:
print(unique_counts)

col_0      100
col_1      100
col_2      100
col_3      100
col_4      100
col_5      100
col_6      100
col_7      100
col_8      100
col_9      100
col_10     100
col_11     100
col_12     100
col_13     100
col_14     100
col_15     100
col_16     100
col_17     100
col_18     100
col_19     100
col_20     100
col_21     100
col_22     100
col_23     100
col_24     100
col_25     100
col_26     100
col_27     100
col_28     100
col_29     100
col_30     100
col_31     100
col_32     100
col_33     100
col_34     100
col_35     100
col_36     100
col_37     100
col_38     100
col_39     100
col_40     100
col_41     100
col_42     100
col_43     100
col_44     100
col_45     100
col_46     100
col_47     100
col_48     100
col_49     100
col_50     100
col_51     100
col_52     100
col_53     100
col_54     100
col_55     100
col_56     100
col_57     100
col_58     100
col_59     100
col_60     100
col_61     100
col_62     100
col_63     100
col_64     100
col_65     100
col_66     100
col_67     100
col_68     100
col_69     100
col_70     100
col_71     100
col_72     100
col_73     100
col_74     100
col_75     100
col_76     100
col_77     100
col_78     100
col_79     100
col_80     100
col_81     100
col_82     100
col_83     100
col_84     100
col_85     100
col_86     100
col_87     100
col_88     100
col_89     100
col_90     100
col_91     100
col_92     100
col_93     100
col_94     100
col_95     100
col_96     100
col_97     100
col_98     100
col_99     100
col_100    100
col_101    100
col_102    100
col_103    100
col_104    100
col_105    100
col_106    100
col_107    100
col_108    100
col_109    100
col_110    100
col_111    100
col_112    100
col_113    100
col_114    100
col_115    100
col_116    100
col_117    100
col_118    100
col_119    100
col_120    100
col_121    100
col_122    100
dtype: int64

In [ ]:
pd.set_option()